import streamlit as st
import streamlit.components.v1 as components
import random
import uuid

from services.news_service import (
    fetch_news,
    extract_full_article
)

from services.explanation_service import (
    generate_explanation,
    generate_deep_context
)

from utils.text_cleaner import (
    clean_article_text,
    filter_relevant_content
)

# ─────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────

st.set_page_config(
    page_title="AI News Intelligence",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# ─────────────────────────────────────────────
# SESSION STORAGE
# ─────────────────────────────────────────────

if "articles" not in st.session_state:
    st.session_state.articles = []

if "refresh_token" not in st.session_state:
    st.session_state.refresh_token = str(uuid.uuid4())

if "expanded_article_uid" not in st.session_state:
    st.session_state.expanded_article_uid = None

# ─────────────────────────────────────────────
# HARD REFRESH ENGINE
# ─────────────────────────────────────────────

def perform_hard_refresh():
    keys_to_remove = []
    for key in st.session_state.keys():
        if (
            key.startswith("summary_")
            or
            key.startswith("context_")
        ):
            keys_to_remove.append(key)

    for key in keys_to_remove:
        del st.session_state[key]

    st.session_state.refresh_token = str(uuid.uuid4())
    st.session_state.expanded_article_uid = None

    fresh_articles = fetch_news(
        region=st.session_state.region_selector,
        category=st.session_state.category_selector
    )

    unique_articles = []
    seen_links = set()
    for article in fresh_articles:
        if article["link"] not in seen_links:
            unique_articles.append(article)
            seen_links.add(article["link"])

    random.shuffle(unique_articles)
    st.session_state.articles = unique_articles[:8]

# ─────────────────────────────────────────────
# INITIAL FETCH
# ─────────────────────────────────────────────

if not st.session_state.articles:
    initial_articles = fetch_news(
        region="India",
        category="All"
    )
    random.shuffle(initial_articles)
    st.session_state.articles = initial_articles[:8]

# ─────────────────────────────────────────────
# THEME CONFIGURATION
# ─────────────────────────────────────────────

BG = "#181825"
CARD_BG = "rgba(36, 33, 58, 0.68)"
CARD_BORDER = "rgba(180, 167, 255, 0.10)"
TEXT = "#F5F3FF"
TEXT_SOFT = "#B7B2D9"
ACCENT = "#B4A7FF"
ACCENT_LIGHT = "#CFC7FF"
SUMMARY_BG = "rgba(56, 50, 84, 0.45)"
CONTEXT_BG = "rgba(48, 44, 76, 0.52)"
SHADOW = "0 6px 24px rgba(0,0,0,0.18)"

# ─────────────────────────────────────────────
# CSS SYSTEM OVERRIDES (FIXES ACCORDION OVERLAP)
# ─────────────────────────────────────────────

st.markdown(f"""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');

html, body, .stApp {{
    background: {BG};
    color: {TEXT};
    font-family: 'Inter', sans-serif;
}}

#MainMenu, footer, header {{
    visibility: hidden;
    display: none;
}}

[data-testid="stDecoration"] {{
    display: none;
}}

.block-container {{
    max-width: 1120px;
    padding-top: 2.5rem;
    padding-bottom: 4rem;
}}

/* Clean out empty wrapper spaces generated by internal script rendering */
[data-testid="stVerticalBlock"] > div:has(div.stMarkdown:empty),
[data-testid="stVerticalBlock"] > div:empty,
div:empty {{
    display: none !important;
    height: 0px !important;
    margin: 0px !important;
    padding: 0px !important;
}}

[data-testid="stVerticalBlock"] {{
    gap: 0rem !important;
}}

.main-title {{
    text-align: center;
    font-size: clamp(2.2rem, 5vw, 3.3rem);
    font-weight: 800;
    margin-bottom: 0.3rem;
    background: linear-gradient(135deg, {ACCENT}, {ACCENT_LIGHT});
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}}

.sub-title {{
    text-align: center;
    color: {TEXT_SOFT};
    font-size: 1rem;
    margin-bottom: 2.5rem;
}}

.filter-panel {{
    background: {CARD_BG};
    border: 1px solid {CARD_BORDER};
    backdrop-filter: blur(18px);
    border-radius: 24px;
    padding: 1.2rem;
    margin-bottom: 2rem;
    box-shadow: {SHADOW};
}}

/* 🎯 RECTIFICATION OVERRIDE: Adds an intentional half-inch space and prevents card overlap */
.accordion-card {{
    background: {CARD_BG};
    border: 1px solid {CARD_BORDER};
    backdrop-filter: blur(16px);
    border-radius: 20px;
    padding: 0.5rem;
    margin-bottom: 24px !important; /* Fixed half-inch layout margin */
    box-shadow: {SHADOW};
    position: relative !important;
    display: block !important;
    clear: both !important;
    height: auto !important;
}}

.inner-content-padding {{
    padding: 0.5rem 1.4rem 1.2rem 1.4rem;
}}

/* 🎯 FULLY INTEGRATED ACCORDION ACTIONS (Replaces st.columns loop bug) */
.title-container-btn div[data-testid="stButton"] > button {{
    background: transparent !important;
    border: none !important;
    color: {TEXT} !important;
    font-size: 1.2rem !important;
    font-weight: 700 !important;
    text-align: left !important;
    line-height: 1.55 !important;
    padding: 1.1rem 1.4rem !important;
    width: 100% !important;
    box-shadow: none !important;
    transform: none !important;
    display: flex !important;
    justify-content: space-between !important;
    align-items: center !important;
    gap: 1.5rem !important;
    height: auto !important;
    min-height: unset !important;
    border-radius: 16px !important;
}}

.title-container-btn div[data-testid="stButton"] > button:hover {{
    color: {ACCENT_LIGHT} !important;
    background: rgba(180, 167, 255, 0.05) !important;
}}

/* Responsive integrated arrow marker inside layout borders */
.title-container-btn div[data-testid="stButton"] > button::after {{
    content: "▼";
    font-size: 0.9rem;
    color: {ACCENT};
    font-weight: bold;
    flex-shrink: 0;
    transition: transform 0.2s ease;
}}

.title-container-btn.open div[data-testid="stButton"] > button::after {{
    content: "▲" !important;
    color: {ACCENT_LIGHT};
}}

.source-badge {{
    display: inline-flex;
    align-items: center;
    padding: 0.38rem 0.85rem;
    border-radius: 999px;
    background: rgba(180,167,255,0.08);
    color: {ACCENT_LIGHT};
    font-size: 0.72rem;
    font-weight: 700;
    margin-bottom: 1.2rem;
    border: 1px solid rgba(180,167,255,0.12);
}}

.summary-box {{
    background: {SUMMARY_BG};
    border: 1px solid rgba(180,167,255,0.08);
    border-radius: 20px;
    padding: 1.1rem 1.2rem;
    margin-bottom: 1.2rem;
    line-height: 1.85;
    font-size: 0.98rem;
}}

.context-box {{
    background: {CONTEXT_BG};
    border: 1px solid rgba(180,167,255,0.08);
    border-radius: 20px;
    padding: 1.1rem 1.2rem;
    margin-top: 1.2rem;
    line-height: 1.9;
    font-size: 0.96rem;
}}

.box-label {{
    display: block;
    font-size: 0.72rem;
    font-weight: 800;
    letter-spacing: 1px;
    margin-bottom: 0.6rem;
    color: {ACCENT};
    text-transform: uppercase;
}}

/* Dashboard UI Control Layout Definitions */
div[data-testid="stButton"] > button {{
    height: 50px;
    border-radius: 16px;
    border: 1px solid rgba(180,167,255,0.10);
    background: rgba(180,167,255,0.06);
    color: #E8E2FF;
    font-weight: 700;
    font-size: 0.92rem;
    transition: all 0.2s ease;
}}

div[data-testid="stButton"] > button:hover {{
    background: rgba(180, 167, 255, 0.12);
    border-color: rgba(180, 167, 255, 0.18);
    transform: translateY(-1px);
}}

.read-link {{
    display: flex;
    align-items: center;
    justify-content: center;
    height: 50px;
    border-radius: 16px;
    background: rgba(180,167,255,0.06);
    border: 1px solid rgba(180,167,255,0.10);
    color: #E8E2FF !important;
    text-decoration: none !important;
    font-weight: 700;
    font-size: 0.92rem;
    transition: all 0.2s ease;
}}

.read-link:hover {{
    background: rgba(180, 167, 255, 0.12);
    transform: translateY(-1px);
}}

/* Cross-device system screen layouts fluid parameters */
@media (max-width: 768px) {{
    .block-container {{ max-width: 100%; padding: 1rem; }}
    div[data-testid="stButton"] > button {{ height: 46px; }}
    .read-link {{ height: 46px; }}
    .title-container-btn div[data-testid="stButton"] > button {{ font-size: 1.1rem !important; padding: 0.9rem 1rem !important; }}
    .accordion-card {{ margin-bottom: 16px !important; }}
}}
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# HEADER
# ─────────────────────────────────────────────

st.markdown("""
<div id="top"></div>
<div class="main-title">🧠 AI News Intelligence</div>
<div class="sub-title">Real-time News Explained Clearly with AI</div>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# FILTER PANEL
# ─────────────────────────────────────────────

st.markdown('<div class="filter-panel">', unsafe_allow_html=True)
c1, c2, c3 = st.columns([1.5, 2.2, 1.2])

with c1:
    region = st.segmented_control(
        "🌍 Region",
        options=["India", "World"],
        default="India",
        key="region_selector",
        on_change=perform_hard_refresh
    )

with c2:
    category = st.selectbox(
        "📂 Category",
        ["All", "Politics", "Technology", "Finance", "Sports", "Entertainment"],
        key="category_selector",
        on_change=perform_hard_refresh
    )

with c3:
    st.markdown("<div style='height:28px'></div>", unsafe_allow_html=True)
    st.button(
        "🔄 Refresh",
        use_container_width=True,
        on_click=perform_hard_refresh
    )

st.markdown("</div>", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# ARTICLE FEED STREAM PROCESSING
# ─────────────────────────────────────────────

articles = st.session_state.articles

if not articles:
    st.warning("No fresh articles available currently.")

for article in articles:
    article_id = (
        article["title"]
        .replace(" ", "_")
        .replace("/", "")
        .replace(":", "")
        [:80]
    )

    summary_key = f"summary_{article_id}_{st.session_state.refresh_token}"
    context_key = f"context_{article_id}_{st.session_state.refresh_token}"
    
    is_currently_expanded = (st.session_state.expanded_article_uid == article_id)

    # Accordion Card Shell Wrapper
    st.markdown('<div class="accordion-card">', unsafe_allow_html=True)
    
    # Render interactive title block with integrated flex indicators
    btn_class = "title-container-btn open" if is_currently_expanded else "title-container-btn"
    st.markdown(f'<div class="{btn_class}">', unsafe_allow_html=True)
    if st.button(article["title"], key=f"title_trigger_{article_id}", use_container_width=True):
        if is_currently_expanded:
            st.session_state.expanded_article_uid = None
        else:
            st.session_state.expanded_article_uid = article_id
        st.rerun()
    st.markdown('</div>', unsafe_allow_html=True)

    # Expanded Deep Analytics view block
    if is_currently_expanded:
        st.markdown('<div class="inner-content-padding">', unsafe_allow_html=True)
        st.markdown(f'<div class="source-badge">📡 {article["source"]}</div>', unsafe_allow_html=True)

        cleaned_text = clean_article_text(article["summary"])
        filtered_text = filter_relevant_content(article["title"], cleaned_text)

        if summary_key not in st.session_state:
            with st.spinner("Generating AI summary..."):
                st.session_state[summary_key] = generate_explanation(
                    article["title"],
                    filtered_text
                )

        st.markdown(f"""
<div class="summary-box">
<span class="box-label">✨ AI Summary</span>
{st.session_state[summary_key]}
</div>
""", unsafe_allow_html=True)

        col_btn1, col_btn2 = st.columns([1.2, 1.6])

        with col_btn1:
            if st.button(
                "🔍 More Context",
                key=f"context_button_{article_id}_{st.session_state.refresh_token}",
                use_container_width=True
            ):
                if context_key not in st.session_state:
                    with st.spinner("Generating deep context..."):
                        full_text = extract_full_article(article["link"])
                        context_source = full_text if full_text else article["summary"]
                        context_cleaned = filter_relevant_content(article["title"], context_source)
                        st.session_state[context_key] = generate_deep_context(
                            article["title"],
                            context_cleaned
                        )
                    st.rerun()

        with col_btn2:
            st.markdown(f"""
<a class="read-link" href="{article["link"]}" target="_blank">📰 Read Original Article</a>
""", unsafe_allow_html=True)

        if context_key in st.session_state:
            st.markdown(f"""
<div class="context-box">
<span class="box-label">🌍 Deep Context</span>
{st.session_state[context_key]}
</div>
""", unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True) # End inner content padding

    st.markdown('</div>', unsafe_allow_html=True)

# ─────────────────────────────────────────────
# BACK TO TOP BUTTON (NATIVE HTML/JS ANCHOR)
# ─────────────────────────────────────────────
st.markdown('<a href="#top" id="premiumScrollTopBtn" class="read-link" style="position:fixed; bottom:24px; right:24px; width:52px; height:52px; border-radius:50%; display:none; align-items:center; justify-content:center; font-size:22px; z-index:999999; box-shadow:0 8px 24px rgba(0,0,0,0.28); text-decoration:none !important;">↑</a>', unsafe_allow_html=True)

js_scroll_fix = """
<script>
(function () {
    const btn = window.parent.document.getElementById("premiumScrollTopBtn");
    const scrollTarget = window.parent.document.querySelector('[data-testid="stAppViewContainer"]') || window.parent;
    if(btn && scrollTarget) {
        scrollTarget.addEventListener("scroll", function () {
            if (scrollTarget.scrollTop > 250 || window.parent.scrollY > 250) {
                btn.style.setProperty('display', 'flex', 'important');
            } else {
                btn.style.setProperty('display', 'none', 'important');
            }
        }, { passive: true });
        btn.addEventListener("click", function (e) {
            e.preventDefault();
            scrollTarget.scrollTo({ top: 0, behavior: "smooth" });
        });
    }
})();
</script>
"""
components.html(js_scroll_fix, height=0)